#!/usr/bin/env node
/**
 * Renders `PRESENTATION-SLIDES.md` from the canonical slide data in
 * `src/presentation.json`.
 *
 * This never touches the supplied `PRESENTATION.md` run sheet — that document is the
 * presenter's own guide and stays hand-written.
 *
 *   node scripts/presentation.mjs --write   regenerate the file
 *   node scripts/presentation.mjs --check   fail if the file is out of date
 */

import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const sourcePath = join(root, 'src', 'presentation.json');
const targetPath = join(root, 'PRESENTATION-SLIDES.md');

const HEADER = `<!-- Generated by \`npm run presentation:write\` from src/presentation.json. -->
<!-- Edit src/presentation.json, not this file. -->

# Presentation slides

Slide content and speaker notes for the Decision Lab talk. The timing plan, the mode
statement, and the rehearsal guidance live in [PRESENTATION.md](PRESENTATION.md).
`;

function renderSlide(slide) {
  const lines = [`## ${String(slide.number).padStart(2, '0')} · ${slide.title}`, ''];
  lines.push(`**Timing:** ${slide.timing}  `);
  lines.push(`**Eyebrow:** ${slide.eyebrow}`);

  if (slide.kicker) {
    lines.push(`**Kicker:** ${slide.kicker}`);
  }

  lines.push('');
  lines.push(slide.subtitle);
  lines.push('');

  if (slide.cards) {
    for (const card of slide.cards) {
      lines.push(`### ${card.title}`);
      lines.push('');
      for (const line of card.lines) {
        lines.push(`- ${line}`);
      }
      if (card.footer) {
        lines.push('');
        lines.push(`> ${card.footer}`);
      }
      lines.push('');
    }
  }

  lines.push(`> ${slide.pullQuote}`);
  lines.push('');
  lines.push('**Speaker notes**');
  lines.push('');
  for (const note of slide.notes) {
    lines.push(`- ${note}`);
  }
  lines.push('');

  return lines.join('\n');
}

function render(document) {
  const slides = document.slides.map(renderSlide).join('\n');
  return `${HEADER}\n${slides}`;
}

async function main() {
  const mode = process.argv.includes('--write') ? 'write' : 'check';
  const document = JSON.parse(await readFile(sourcePath, 'utf8'));
  const expected = render(document);

  if (mode === 'write') {
    await writeFile(targetPath, expected, 'utf8');
    console.log(`Wrote PRESENTATION-SLIDES.md (${document.slides.length} slides).`);
    return;
  }

  let actual;
  try {
    actual = await readFile(targetPath, 'utf8');
  } catch {
    console.error('PRESENTATION-SLIDES.md is missing. Run `npm run presentation:write`.');
    process.exitCode = 1;
    return;
  }

  if (actual !== expected) {
    console.error('PRESENTATION-SLIDES.md is out of date. Run `npm run presentation:write`.');
    process.exitCode = 1;
    return;
  }

  console.log(
    `PRESENTATION-SLIDES.md matches src/presentation.json (${document.slides.length} slides).`,
  );
}

await main();
